apiVersion: apps/v1
kind: Deployment
metadata:
    name: abc-technologies
    labels:
        app: myapp
spec:           
    replicas: 1
    selector:
        matchLabels:
            app: myapp
    template:      
        metadata:
            labels:
                app: myapp
        spec:                  
            containers:
                - name: c1
                  image: ashokdevatwal78/abc-technologies:latest
                            
---                       
apiVersion: v1
kind: Service
metadata:
    name: myapp-svc
spec:   
    type: NodePort
    selector:
        app: myapp
    ports:  
        - port: 80
          targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
spec:
    containers:
        - name: c1
          image: ashokdevatwal78/abc-technologies:latest
